#!/bin/bash

set -x

cd virtualbox/steps/data/puppet
# puppet has strange exit codes. success in our case means 2
/opt/puppetlabs/bin/puppet apply --test --detailed-exitcodes --debug --modulepath modules:/etc/puppetlabs/code/environments/production/modules manifests/$1.pp
ret=$?
echo Puppet exit code: $ret
[ "$ret" = "2" ]
